### ISSUE TITLE
Error with fresh Lyra installation

### ISSUE THREAD

**Issue by mateonunez** [nearform/lyra#27]
**Describe the bug**
I've created a new project where I wanted to implement Lyra, so I've added it as a dependency. When I've try to import `Lyra`, I get the following output error:

```
❯ npm run test

> new-lyra@1.0.0 test
> node index.js

node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '~/dev/new-lyra/node_modules/@nearform/lyra/' imported from ~/dev/new-lyra/index.js
```

**To Reproduce**
1. Create a new empty JS project: `npm init --yes`
2. Install Lyra as a dependency: `npm install @nearform/lyra`
3. Create a simple file that imports `Lyra`.
4. Run it.

**Screenshots**

This is the content of Lyra's directory inside `node_modules`

![image](https://user-images.githubusercontent.com/11861080/179494118-228a6d96-3cc2-421c-9192-2417bc22e2a0.png)

**Desktop (please complete the following information):**
 - OS: **macOS Monterey 12.4**
 - Environment: **Node**
 - Node: **v18.6.0**
 - npm: **v8.14.0**
 - Lyra: **v0.0.1-beta-11**

**Additional context**

I've created a [repository](https://github.com/mateonunez/lyra-fresh-installation) with the reproduced error hoping it could be useful.

**Comment by micheleriva** [comment]
Should be fixed in v0.0.1-beta-12 🙂

**Comment by mateonunez** [comment]
Sorry for commenting a closed issue @micheleriva, but I wanna let you know that the error persists even with the `v0.0.1-beta-12` version.

**Comment by thomscoder** [comment]
> Sorry for commenting a closed issue @micheleriva, but I wanna let you know that the error persists even with the `v0.0.1-beta-12` version.

i confirm. index.js keeps not getting created. 
Tested on both Monterey 12.4 and Windows 10 Pro

**Comment by micheleriva** [comment]
Fixed and tested on `0.0.1-beta-13`

Thanks!
